In [3]:
import numpy as np
import pandas as pd

In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv(r"C:\Users\Vaishnavi\OneDrive\Desktop\project final\customer_shopping_data.csv")
data.info()
data.isnull().sum()
data['invoice_date']=pd.to_datetime(data['invoice_date'], format='%d-%m-%Y', errors='coerce')

#here  we created new column 
label=['Young Adult','Adult','Middle-Aged','Senior']

data["Aged_Group"]=pd.qcut(data["age"],q=4,labels=label)

data["Sales"]=data["price"] * data["quantity"]

data.columns=data.columns.str.title()

pip install psycopg2-binary sqlalchemy

from sqlalchemy import create_engine

# Step 1: Connection details
username = "postgres"
password = "root"      # replace with your password
host = "localhost"
port = "5432"
database = "customer_shopping_data"

# Step 2: Create connection engine
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 3: Load DataFrame into PostgreSQL
table_name = "customer"   # you can change table name

data.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

In [4]:
data=pd.read_csv(r"C:\Users\Vaishnavi\OneDrive\Desktop\project final\customer_shopping_data.csv")

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

In [6]:
data.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [7]:
#conver date(object) into to_date

data['invoice_date']=pd.to_datetime(data['invoice_date'], format='%d-%m-%Y', errors='coerce')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  datetime64[ns]
 9   shopping_mall   99457 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 7.6+ MB

In [9]:
#here  we created new column 
label=['Young Adult','Adult','Middle-Aged','Senior']

data["Aged_Group"]=pd.qcut(data["age"],q=4,labels=label)

In [10]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,Aged_Group
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,Young Adult
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,Young Adult
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,Young Adult
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,Senior
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,Middle-Aged
...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,2022-09-21,Kanyon,Middle-Aged
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,2021-09-22,Forum Istanbul,Young Adult
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,2021-03-28,Metrocity,Senior
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,2021-03-16,Istinye Park,Middle-Aged
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,2022-10-15,Mall of Istanbul,Adult

In [11]:
data["Sales"]=data["price"] * data["quantity"]

In [12]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,Aged_Group,Sales
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,Young Adult,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,Young Adult,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,Young Adult,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,Senior,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,Middle-Aged,242.40
...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,2022-09-21,Kanyon,Middle-Aged,293.25
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,2021-09-22,Forum Istanbul,Young Adult,20.92
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,2021-03-28,Metrocity,Senior,20.92
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,2021-03-16,Istinye Park,Middle-Aged,16800.00
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,2022-10-15,Mall of Istanbul,Adult,105.57

In [13]:
data.columns=data.columns.str.title()

In [14]:
data

,Invoice_No,Customer_Id,Gender,Age,Category,Quantity,Price,Payment_Method,Invoice_Date,Shopping_Mall,Aged_Group,Sales
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,Young Adult,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,Young Adult,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,Young Adult,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,Senior,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,Middle-Aged,242.40
...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,2022-09-21,Kanyon,Middle-Aged,293.25
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,2021-09-22,Forum Istanbul,Young Adult,20.92
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,2021-03-28,Metrocity,Senior,20.92
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,2021-03-16,Istinye Park,Middle-Aged,16800.00
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,2022-10-15,Mall of Istanbul,Adult,105.57

In [15]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\vaishnavi\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in d:\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
from sqlalchemy import create_engine

# Step 1: Connection details
username = "postgres"
password = "root"      # replace with your password
host = "localhost"
port = "5432"
database = "customer_shopping_data"

# Step 2: Create connection engine
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 3: Load DataFrame into PostgreSQL
table_name = "customer"   # you can change table name

data.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_shopping_data'.

In [21]:
data.columns

Index(['Invoice_No', 'Customer_Id', 'Gender', 'Age', 'Category', 'Quantity',
       'Price', 'Payment_Method', 'Invoice_Date', 'Shopping_Mall',
       'Aged_Group', 'Sales'],
      dtype='object')